version: 2
updates:
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  # Docker Images
  - package-ecosystem: "docker"
    directory: "/authelia"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/caddy"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "caddy"
    labels:
      - "dependencies"
      - "automated-merge"

  - package-ecosystem: "docker"
    directory: "/crowdsec"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/frigate"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/home-assistant"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/mosquitto"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/pihole"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/postfix-relay"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/redis"
    schedule:
      interval: "daily"
