version: 2
updates:
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Docker Images
  - package-ecosystem: "docker"
    directory: "/authelia"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/caddy"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/crowdsec"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/frigate"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/home-assistant"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/mosquitto"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/pihole"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/postfix-relay"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/redis"
    schedule:
      interval: "weekly"
