# Upstream image pinned to immutable digest for supply chain security
FROM redis:alpine@sha256:2afba59292f25f5d1af200496db41bea2c6c816b059f57ae74703a50a03a27d0

# Add any customisation below this line
