# Upstream image pinned to immutable digest for supply chain security
FROM crowdsecurity/crowdsec:v1.8.1@sha256:0f2523fa61ef507f15d953045cface490cc880670c62f2755ced17524107f71a

# Add any customisation below this line
